# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: builder-testnet
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: BuilderBonding
    address:
    - 0x0897db4a5a3893da383e1e0dfba5634a83551f6780936bd6f1920e865d4fb646
    abi_file_path: abis/builderbonding-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: NewPositionEvent
      logId: '18159118810335600742'
    - name: PositionBondingEvent
      logId: '12148335578419144354'
    - name: RewardsClaimedEvent
      logId: '11232430981972343695'
    - name: PositionDepositEvent
      logId: '7872304445726396561'
    - name: BuilderRewardsExtendedEvent
      logId: '12825160085427872429'
    - name: PositionWithdrawEvent
      logId: '3342276803466707238'
    - name: BaseRewardsSyncedEvent
      logId: '16714692388459207143'
    - name: ParametersSetEvent
      logId: '17952413627041958220'
    - name: NewBuilderEvent
      logId: '15199682701450152254'
    - name: BuilderOwnershipTransferredEvent
      logId: '4110241452629244490'
    - name: OwnershipTransferredEvent
      logId: '8614244114039074780'
    - name: BuilderRewardsFundedEvent
      logId: '274950752963923605'
    - name: Transfer
    - name: Mint
    - name: Burn

